### ISSUE TITLE
Inforácie o trénovacích dátach 

### ISSUE THREAD

**Issue by Bori65** [essential-data/word2vec-sk#1]
Dobrý deň,
mohli by ste mi prosím poskytnúť nejaké informácie o dátach, na ktorých bol natrénovaný tento model (či napríklad išlo o wiki stránky, mediálne obsahy alebo iné kategórie)?  Nakoľko mám porovnať word2vec model so SlovakBERT modelom, kde berieme do úvahy aj typ a rozsah trénovacích dát.

**Comment by jooray** [comment]
Jednalo sa o Korpus slovenského jazyka z Jazykovedného ústavu Ľudovíta Štúra. Korpus samotný nie je verejne dostupný, trénovali sme na dočasne sprístupnených dátach. Viac informácií tu:

https://korpus.juls.savba.sk/

Korpus sme "zlematizovali", teda všetky slová sú v základnom tvare.
